const list = [
    {
      id: 1,
      title: "Harry Potter and the Philosopher's Stone",
      author: "Novel by J. K. Rowling",
      price: 45,
      img: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTQ9LFglH_i7X2DcF1jR3m0UKhpnmFDu3YCjy9e2Wxca7v8lrvo",
      amount: 1,
    },
    {
      id: 2,
      title: "Harry Potter and the Cursed Child",
      author: "Play by J. K. Rowling, Jack Thorne, and John Tiffany",
      price: 96,
      img: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQxDjAcsYHiLd8EEToeE6KdnQsYqjIFWGw7iMsBm7eT9A89UvTJ",
      amount: 1,
    },
    {
      id: 3,
      title: "Harry Potter and the Chamber of Secrets",
      author: "Novel by J. K. Rowling",
      price: 145,
      img: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQ-wNr_rVKT8dZpgIK7G1DC9wUxNzwscowfs1pEkklwbUZZH6g0",
      amount: 1,
    },
    {
      id: 4,
      title: "Harry Potter and the Goblet of Fire",
      author: "Novel by J. K. Rowling",
      price: 57,
      img: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTwZBae2nt9Y_2XoBrF-TSx04bpzrIJzDgZgPh21HMuilj1clNk",
      amount: 1,
    },
    {
      id: 5,
      title: "Harry Potter and the Order of the Phoenix",
      author: "Novel by J. K. Rowling",
      price: 120,
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgHoWEJNFU8777dB_EMlIfxwuw4qbiazSulBFWw_D-cEOLleTx",
      amount: 1,
    },
    {
      id: 6,
      title: "Harry Potter and the Half-Blood Prince",
      author: "Novel by J. K. Rowling",
      price: 135,
      img: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTcgXlBrmzr2lFqxSIUgInwFEVTB2XZ0UIzlbNc8UhPMxU6rAd9",
      amount: 1,
    },
    {
      id: 7,
      title: "Pre-School Activities Pack ",
      author: "by Om Books Editorial Team  | 1 January 2021",
      price: 693,
      img: "https://m.media-amazon.com/images/I/913sv4sex3L._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 8,
      title: "Early Learning Library Pack 1",
      author: "by Wonder House Books  | 6 December 2020",
      price: 289,
      img: "https://m.media-amazon.com/images/I/71xMttNhr7L._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 9,
      title: "Blossom Moral Story Book for Kids ",
      author: "by Content Team at Target Publications",
      price: 80,
      img: "https://m.media-amazon.com/images/I/7122h3jWvEL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 10,
      title: "Brain Activity Book for Kids",
      author: "by Maple Press | 1 September 2021",
      price: 86,
      img: "https://m.media-amazon.com/images/I/7175YpTSa7L._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 11,
      title: "Willy the Silly Panda",
      author: "by Rebecca Smith  | 14 December 2021",
      price: 120,
      img: "https://m.media-amazon.com/images/I/71-ocPGQIJL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
    {
      id: 12,
      title: "Grandma's Bag of Stories",
      author: "by Sudha Murty | 1 January 2015",
      price: 157,
      img: "https://m.media-amazon.com/images/I/81jv44QdNwL._AC_UY327_FMwebp_QL65_.jpg",
      amount: 1,
    },
  ];
  
  export default list;